# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build native image on self-hosted runner & upload it

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn -Pnative-image package --file pom.xml
    - uses: actions/upload-artifact@v2
      with:
        name: primes
        path: target/org.shelajev.primes.primes.primesapplication
